[package]
name = "syslua-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }
syslua-lib = { workspace = true }
